feat: Support sorting on primary key fields
tigrisdata/tigris pull request #1091
Opened 2023-04-25 00:34 UTC by himank

## Describe your changes
- Refactoring query planner
- Honoring the sorting if it is on primary key fields
- Strictly enforcing sorting on a single field for database queries. 

## How best to test these changes

## Issue ticket number and link

2023-04-25 08:08 UTC, garrensmith requested changes
Some small changes but this is looking good.

2023-04-25 08:08 UTC, garrensmith commented on query/filter/key_builder.go
> +	for _, idx := range indexableFields {
Thanks for the spelling fix.

2023-04-25 08:08 UTC, garrensmith commented on server/services/v1/database/query_planner.go
> +type PrimaryIndexPlanner struct {
This is very nice

2023-04-25 15:42 UTC, himank commented on query/filter/key_builder.go
> +			if e.Type() == OrOP && k.indexType == SecondaryIndex {
Sure

2023-04-25 16:49 UTC, himank commented on server/services/v1/database/base_runner.go
>  	for i, sf := range *ordering {
That's right, `InMemoryName` is our alias in search only to avoid conflicts.

2023-04-26 01:12 UTC, efirs approved these changes

2023-04-26 01:41 UTC, merged